### PR TITLE
In dev

### PR DESCRIPTION
**Pull request by Popov-Dmitriy-Ivanovich**
added cast system for numeric type

### CODE REVIEW

**Comment by polyntsov** [comment]
О правилах наименовая коммитов и пулреквестов есть в [wiki](https://github.com/Mstrutov/Desbordante/wiki/Development), прочти. Пулреквесты в разработке можно помечать как draft

**Comment by Popov-Dmitriy-Ivanovich** [comment]
> added cast system for numeric type

Removed warnings during compilation, hope tests will pass. Have no idea what to do with clang-format-check

**Comment by polyntsov** [comment]
> Removed warnings during compilation, hope tests will pass. Have no idea what to do with clang-format-check

You can click the "details" button next to the check and then the "summary" button in the upper left corner, a page will appear with all the formatting violations in your patches that need to be fixed. You can do it either manually, or by using `clang-format` tool, but please apply automatic formatting **only** on your changes, not entire files.

Also the commit messages still have incorrect naming style, follow the [commit message rules](https://cbea.ms/git-commit/) (taken from our wiki).
And, please, try to keep commit history as clean as possible, prefer overwriting existing commits with useful functionality instead of adding new commits with "fixups" (useful blog post on the topic https://mainmatter.com/blog/2021/05/26/keeping-a-clean-git-history/, especially the "Smallest number of commits for the smallest conceptual change" paragraph).

**Comment by Popov-Dmitriy-Ivanovich** [comment]
Думаю лучше будет починить названия коммитов закомитив их в другую ветку и PR кинуть оттуда

**Comment by polyntsov** [comment]
Все равно скорее всего придется исправлять существующие коммиты после ревью, поэтому не очень понятно, зачем нужна новая ветка и отдельный pr

**Pull request closed without merging**
